repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: ['--maxkb=20000']
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    #-   id: pretty-format-json
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        exclude: notebooks
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest kaggle_storesales_forecasting
        language: system
        pass_filenames: false
        always_run: true
        args: ['-v']
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black", --line-length=72]
default_stages: [commit, push]
